Fix missing deno version on deploy
Using latests version of deno, amqp fail at runtime because Deno.version is undefined.

This is the detail of the error that I get using that library on supabase edge function based on deno.

TypeError: Cannot read properties of undefined (reading 'deno')
    at https://deno.land/x/amqp@v0.21.0/src/amqp_connection.ts:12:36